---
title: "GlobalStd"
author: "Miao Yu"
date: '2018-03-23'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Inputs and Outputs

```{r globalstd, echo=FALSE}
library(enviGCMS)
inputPanel(
  h4('Uploading File'),
  br(),
  fileInput('file',label = 'csv file with m/z, retention time, peaklist and group info',accept = c('.csv')),
  br(),
  
  sliderInput("rtcutoff", label = "Cutoff for retention time cluster:",
              min = 1, max = 20, value = 9, step = 1),
  br(),
  sliderInput("freqcutoff", label = "Cutoff for freqency of paired mass differences within RT cluster:",
              min = 5, max = 50, value = 30, step = 1),
  br(),
  sliderInput("pmdcutoff", label = "Cutoff for the largest paired mass differences within RT cluster:",
              min = 50, max = 1000, value = 100, step = 10),
  br(),
  sliderInput("rtcutoff2", label = "Cutoff for the largest retention time differences for std peaks:",
              min = 0, max = 20, value = 3, step = 0.5),
  br(),
  sliderInput("freqcutoff2", label = "freqency of paired mass differences between RT cluster for std peaks:",
              min = 0, max = 100, value = 10, step = 5),
  br(),
  sliderInput("pmdcutoff2", label = "Cutoff for the paired mass differences within RT cluster:",
              min = 50, max = 1000, value = 500, step = 10)
  
)
datainput <- reactive({
                if (!is.null(input$file)){
                        dataraw <- read.csv(input$file$datapath,skip = 1)
                        mz <- dataraw[,2]
                        rt <- dataraw[,3]
                        data <- dataraw[,-c(1:3)]
                        group <- data.frame(t(read.csv(input$file$datapath,nrows = 1)[-(1:3)]))
                        colnames(group) <- c(1:ncol(group))
                        colnames(data) <- rownames(group)
                        rownames(data) <- dataraw[,1]
                        return(list(data=data,mz=mz,rt=rt,group=group))
                }else{
                        return(NULL)
                }
        })
datastd <- reactive({
        list <- datainput()
        if(!is.null(list)){
                list <- globalstd(list,input$rtcutoff,input$freqcutoff,pmdcutoff = input$pmdcutoff,rtcutoff2 = input$rtcutoff2,freqcutoff2 = input$freqcutoff2,pmdcutoff2 = input$pmdcutoff2)
        }
        return(list)
})
stdcsv <- reactive({
        list <- datastd()
        data <- cbind(mz = list$mz[list$stdmassindex], rt = list$rt[list$stdmassindex], list$data[list$stdmassindex,])
        data <- t(cbind(group = t(cbind(mz = 'mz',rt = 'rt',t(list$group))), t(data)))
        return(data)
})
# show the download
downloadHandler('globalstd.csv', content = function(file) {
                data <- stdcsv()
                write.csv(data, file)
        })
renderPlot({
        list <- datastd()
        if(!is.null(list)){
                if(sum(list$pairedindex)>0){
                plotrtg(list)
                }else{
                plot(1,1,type = 'n')
                
        }
        }else{
                plot(1,1,type = 'n')
                
        }
})
renderPlot({
        list <- datastd()
        if(!is.null(list)){
                if(sum(list$pairedindex)>0){
                plotpaired(list) 
                }else{
                plot(1,1,type = 'n')
                
        }
                
        }else{
                plot(1,1,type = 'n')
                
        }
})
renderPlot({
        list <- datastd()
        if(!is.null(list)){
                if(sum(list$pairedindex)>0){
                plotstd(list)
                }else{
                plot(1,1,type = 'n')
                
        }
                
        }else{
                plot(1,1,type = 'n')
                
        }
})
renderPlot({
        list <- datastd()
        if(!is.null(list)){
                if(sum(list$pairedindex)>0){
                plotstdsda(list)
                }else{
                plot(1,1,type = 'n')
                
        }
                
        }else{
                plot(1,1,type = 'n')
                
        }
})


```
