// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_get_molecule
List rcpp_get_molecule(std::string formula, int z, int maxisotopes, double resolution, double fwhm);
RcppExport SEXP _enviGCMS_rcpp_get_molecule(SEXP formulaSEXP, SEXP zSEXP, SEXP maxisotopesSEXP, SEXP resolutionSEXP, SEXP fwhmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type maxisotopes(maxisotopesSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type fwhm(fwhmSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_molecule(formula, z, maxisotopes, resolution, fwhm));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_check_golden_rules
List rcpp_check_golden_rules(std::string formula, int z, double min_hc, double max_hc, double max_dbe);
RcppExport SEXP _enviGCMS_rcpp_check_golden_rules(SEXP formulaSEXP, SEXP zSEXP, SEXP min_hcSEXP, SEXP max_hcSEXP, SEXP max_dbeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type min_hc(min_hcSEXP);
    Rcpp::traits::input_parameter< double >::type max_hc(max_hcSEXP);
    Rcpp::traits::input_parameter< double >::type max_dbe(max_dbeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_check_golden_rules(formula, z, min_hc, max_hc, max_dbe));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_score_isotopes
List rcpp_score_isotopes(NumericVector obs_mz, NumericVector obs_int, NumericVector theo_mz, NumericVector theo_int, double tolerance, bool ppm);
RcppExport SEXP _enviGCMS_rcpp_score_isotopes(SEXP obs_mzSEXP, SEXP obs_intSEXP, SEXP theo_mzSEXP, SEXP theo_intSEXP, SEXP toleranceSEXP, SEXP ppmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type obs_mz(obs_mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_int(obs_intSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theo_mz(theo_mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theo_int(theo_intSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type ppm(ppmSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_score_isotopes(obs_mz, obs_int, theo_mz, theo_int, tolerance, ppm));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_decompose_mass
List rcpp_decompose_mass(double mass, double ppm, double mzabs, SEXP elements, std::string minElements, std::string maxElements, int z, int maxisotopes, bool golden_rules, double resolution, double fwhm);
RcppExport SEXP _enviGCMS_rcpp_decompose_mass(SEXP massSEXP, SEXP ppmSEXP, SEXP mzabsSEXP, SEXP elementsSEXP, SEXP minElementsSEXP, SEXP maxElementsSEXP, SEXP zSEXP, SEXP maxisotopesSEXP, SEXP golden_rulesSEXP, SEXP resolutionSEXP, SEXP fwhmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mass(massSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type mzabs(mzabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type elements(elementsSEXP);
    Rcpp::traits::input_parameter< std::string >::type minElements(minElementsSEXP);
    Rcpp::traits::input_parameter< std::string >::type maxElements(maxElementsSEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type maxisotopes(maxisotopesSEXP);
    Rcpp::traits::input_parameter< bool >::type golden_rules(golden_rulesSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type fwhm(fwhmSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_decompose_mass(mass, ppm, mzabs, elements, minElements, maxElements, z, maxisotopes, golden_rules, resolution, fwhm));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_decompose_masses
List rcpp_decompose_masses(NumericVector masses, double ppm, double mzabs, SEXP elements, std::string minElements, std::string maxElements, int z, int maxisotopes, bool golden_rules, double resolution, double fwhm, int nthreads);
RcppExport SEXP _enviGCMS_rcpp_decompose_masses(SEXP massesSEXP, SEXP ppmSEXP, SEXP mzabsSEXP, SEXP elementsSEXP, SEXP minElementsSEXP, SEXP maxElementsSEXP, SEXP zSEXP, SEXP maxisotopesSEXP, SEXP golden_rulesSEXP, SEXP resolutionSEXP, SEXP fwhmSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type masses(massesSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type mzabs(mzabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type elements(elementsSEXP);
    Rcpp::traits::input_parameter< std::string >::type minElements(minElementsSEXP);
    Rcpp::traits::input_parameter< std::string >::type maxElements(maxElementsSEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type maxisotopes(maxisotopesSEXP);
    Rcpp::traits::input_parameter< bool >::type golden_rules(golden_rulesSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type fwhm(fwhmSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_decompose_masses(masses, ppm, mzabs, elements, minElements, maxElements, z, maxisotopes, golden_rules, resolution, fwhm, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_enviGCMS_rcpp_get_molecule", (DL_FUNC) &_enviGCMS_rcpp_get_molecule, 5},
    {"_enviGCMS_rcpp_check_golden_rules", (DL_FUNC) &_enviGCMS_rcpp_check_golden_rules, 5},
    {"_enviGCMS_rcpp_score_isotopes", (DL_FUNC) &_enviGCMS_rcpp_score_isotopes, 6},
    {"_enviGCMS_rcpp_decompose_mass", (DL_FUNC) &_enviGCMS_rcpp_decompose_mass, 11},
    {"_enviGCMS_rcpp_decompose_masses", (DL_FUNC) &_enviGCMS_rcpp_decompose_masses, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_enviGCMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
